const PREFIX = '/reducres/Models/';

export const SET_IS_FETCHING = `${PREFIX}SET_IS_FETCHING`;
export const SET_IS_VIEW_ONLY = `${PREFIX}SET_IS_VIEW_ONLY`;
export const CLEAR_DATA = `${PREFIX}CLEAR_DATA`;

export const SET_WORKBOOK = `${PREFIX}SET_WORKBOOK`;
export const SET_WORKSHEETS = `${PREFIX}SET_WORKSHEETS`;
export const SET_ACTIVE_WORKSHEET = `${PREFIX}SET_ACTIVE_WORKSHEET`;

export const SET_SHARED_MAPPINGS = `${PREFIX}SET_SHARED_MAPPINGS`;
export const SET_GRID_HEADERS = `${PREFIX}SET_GRID_HEADERS`;
export const SET_GRID_DATA = `${PREFIX}SET_GRID_DATA`;
export const SET_FORMULA_CELL_INDEX = `${PREFIX}SET_FORMULA_CELL_INDEX`;
export const DELETE_FORMULA_CELL_INDEX = `${PREFIX}DELETE_FORMULA_CELL_INDEX`;
export const SET_FORMULA_CELLS_INDEX = `${PREFIX}SET_FORMULA_CELLS_INDEX`;

export const SET_ROW_CONFIGS = `${PREFIX}SET_ROW_CONFIGS`;
export const SET_SYSTEM_DIMENSION = `${PREFIX}SET_SYSTEM_DIMENSION`;

export const DEFAULT_GRID_HEADERS = [];
export const DEFAULT_GRID_DATA = [];

export const VIEW_MODES = ['list', 'thumbail'];
export const DEFAULT_VIEW_MODE = VIEW_MODES[1];

export const SET_ASSUMPTION_LISTING = `${PREFIX}SET_ASSUMPTION_LISTING`;
