const PREFIX = '/reducres/RuleBasedModels/';

export const SET_ACTIVE_TAB = `${PREFIX}SET_ACTIVE_TAB`;
export const SET_SINGLE_RBM_DATA = `${PREFIX}SET_SINGLE_RBM_DATA`;
export const SET_OVERVIEW_GRID_DATA = `${PREFIX}SET_OVERVIEW_GRID_DATA`;
export const SET_OVERVIEW_GRID_HEADERS = `${PREFIX}SET_OVERVIEW_GRID_HEADERS`;
export const SET_FORECASTING_GRID_DATA = `${PREFIX}SET_FORECASTING_GRID_DATA`;
export const SET_FORECASTING_GRID_HEADERS = `${PREFIX}SET_FORECASTING_GRID_HEADERS`;
export const SET_FORECASTING_DATA = `${PREFIX}SET_FORECASTING_DATA`;
export const SET_DATE_RANGE = `${PREFIX}SET_DATE_RANGE`;

export const CLEAR_DATA = `${PREFIX}CLEAR_DATA`;
export const CLEAR_FORECASTING_DATA = `${PREFIX}CLEAR_FORECASTING_DATA`;
export const SET_SELECTED_CALCULATION_RULES = `${PREFIX}SET_SELECTED_CALCULATION_RULES`;
export const SET_SELECTED_GROUP_INDEX = `${PREFIX}SET_SELECTED_GROUP_INDEX`;
